# Generated by Django 3.0.2 on 2020-03-18 15:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ec_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='氏名')),
                ('hurigana', models.CharField(max_length=100, verbose_name='フリガナ')),
                ('mail_address', models.CharField(max_length=256, verbose_name='メールアドレス')),
                ('address', models.CharField(max_length=200, verbose_name='住所')),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Tel Number must be entered in the format: '09012345678'. Up to 15 digits allowed.", regex='^[0-9]+$')], verbose_name='電話番号')),
                ('gender', models.BooleanField(blank=True, choices=[(True, '男'), (False, '女')], null=True, verbose_name='性別')),
                ('password', models.CharField(max_length=40, verbose_name='パスワード')),
            ],
        ),
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='本体価格')),
                ('size_d', models.PositiveIntegerField(verbose_name='奥行き')),
                ('size_l', models.PositiveIntegerField(verbose_name='幅')),
                ('size_h', models.PositiveIntegerField(verbose_name='高さ')),
                ('name', models.CharField(max_length=200, verbose_name='商品名')),
                ('description', models.CharField(max_length=500, verbose_name='説明')),
                ('on_sale', models.BooleanField(default=True, verbose_name='販売中')),
                ('soled_amount', models.PositiveIntegerField(default=0, verbose_name='販売個数')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='ec_test.Author')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchandise', to='ec_test.ItemImage')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('total_price', models.PositiveIntegerField(verbose_name='合計金額')),
                ('postage', models.PositiveIntegerField(verbose_name='送料')),
                ('acceptance', models.PositiveSmallIntegerField(choices=[(0, '宅配'), (1, '取りに来る')], verbose_name='受け取り方法')),
                ('payment', models.PositiveIntegerField(choices=[(0, '現金'), (1, 'カード')], verbose_name='支払い方法')),
                ('created_at', models.DateTimeField(verbose_name='注文日時')),
                ('dead_line', models.DateField(verbose_name='納期')),
                ('start_delivery', models.DateTimeField(blank=True, null=True, verbose_name='配送開始日時')),
                ('delivered', models.DateTimeField(verbose_name='取引完了日時')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_history', to='ec_test.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(verbose_name='注文個数')),
                ('price', models.PositiveIntegerField(verbose_name='商品ごと小計')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ec_test.Merchandise', verbose_name='商品')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='ec_test.Order')),
            ],
        ),
    ]
